### ISSUE TITLE
NoSuchMethodError: The method 'replaceAll' was called on null.

### ISSUE THREAD

**Issue by josipbernat** [atiqsamtia/change_app_package_name#7]
Hi,

I have Flutter project and when I try to change bundleId I am getting following crash:

```
Updating build.gradle File
Updating Main Manifest file
Updating Debug Manifest file
Updating Profile Manifest file
Project is using kotlin
Updating MainActivity.kt
Unhandled exception:
NoSuchMethodError: The method 'replaceAll' was called on null.
Receiver: null
Tried calling: replaceAll("xxxxx__old_bundle_id___xxxxx", "xxxxx__new_bundle_id___xxxxx")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      replaceInFile (package:change_app_package_name/file_utils.dart:5:23)
<asynchronous suspension>
#2      AndroidRenameSteps._replace (package:change_app_package_name/android_rename_steps.dart:78:11)
#3      AndroidRenameSteps.updateMainActivity (package:change_app_package_name/android_rename_steps.dart:66:13)
<asynchronous suspension>
#4      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:40:11)
<asynchronous suspension>
#5      ChangeAppPackageName.start (package:change_app_package_name/change_app_package_name.dart:12:40)
#6      main (file:///Users/josipbernat/Software/flutter/.pub-cache/hosted/pub.dartlang.org/change_app_package_name-0.1.2/bin/main.dart:4:24)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by atiqsamtia** [comment]
Interesting!

Would you be able to share **android** directory structure with files list?

**Comment by singhayush1403** [comment]
Getting the same error

**Comment by houdayec** [comment]
Same here.

**Comment by houdayec** [comment]
It would be great to handle error and show which file is not found in project.

**Comment by saigkl** [comment]
Getting the same error.

**Comment by Souvik73** [comment]
I am also getting this error

**Comment by MALLORY8K** [comment]
same here

**Comment by atiqsamtia** [comment]
I tested with different projects and I can't reproduce the error. Can anyone share the directory structure of the android directory here so I could get a better idea?

**Comment by atiqsamtia** [comment]
Fic for this is published to pub.dev Please report if you face the issue again.
